language: ruby
rvm:
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode

gemfile:
  - Gemfile

bundler_args: --without docs support

notifications:
  email: false

branches:
  only:
    - for_zabbix_2_2
